- name: Get windows password  
  ec2_win_password:
    instance_id: i-0778d60757425b85f
    aws_access_key: AKIAIHRFANUXORBWJOBA
    aws_secret_key: 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
    #security_token: "{{ ec2_token }}"
    region: us-east-1
    key_file: "/home/centos/awx-key1.pem"
  register: win_pass
  
- debug : msg="{{ win_pass }}"
