- name: Copy file with owner and permissions
  become: yes
  become_user: root
  copy:
    src: /home/centos/awx-key1.pem
    dest: /root/awx-key1.pem
    owner: root
    group: root
    mode: '0644'


- name: Get windows password  
  ec2_win_password:
    instance_id: i-07b703f2943c1067d
    aws_access_key: AKIAIHRFANUXORBWJOBA
    aws_secret_key: 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
    #security_token: "{{ ec2_token }}"
    region: us-east-1
    key_data: win_key.pem
  register: win_pass
  
- debug : msg="{{ win_pass }}"
